[package]
name = "caveripper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.24.0"
nom = "6.1.2"
encoding_rs = "0.8.28"
itertools = "0.10.1"
regex = "1.5.4"
once_cell = "1.8.0"
image = "0.23"
log = "0.4"

[dependencies.simple_logger]
version = "1.13"
default-features = false
features = ["colors"]

[dev-dependencies]
criterion = "0.3"
rand = {version="0.8", features=["small_rng"]}

[lib]
name = "cavegen"
path = "src/lib.rs"

[[bin]]
name = "caveripper"
path = "src/main.rs"

[[bench]]
name = "benchmark_cavegen"
harness = false
