[package]
name = "caveripper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.24.0"
nom = "6.1.2"
encoding_rs = "0.8.28"
itertools = "0.10.1"
regex = "1.5.4"
once_cell = "1.8.0"
image = "0.23"
