[package]
name = "caveripper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.23.0"
nom = "6.1.2"
encoding_rs = "0.8.28"
