[package]
name = "caveripper"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = {version="7.1", features=["alloc"]}
pest = "2.3"
pest_derive = "2.3"
encoding_rs = "0.8.28"
itertools = "0.10.1"
regex = "1.5.5"
once_cell = "1.8.0"
image = "0.24"
log = "0.4"
clap = {version="3.2", features=["derive"]}
thiserror = "1.0"
fontdue = "0.7.2"
crossbeam = "0.8.2"
rand = {version="0.8", features=["small_rng"]}
indicatif = "0.17"
rayon = "1.5"
serde = {version="1.0", features=["derive"]}

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark_cavegen"
harness = false
