[package]
name = "bindings"
version = "0.0.0"
edition = "2021"

[lib]
name = "caveripper"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
caveripper = {path="../caveripper"}
serde_json = {version="1.0"}
pyo3 = {version="0.17.3", features=["extension-module"]}
